import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex h-screen flex-col items-center justify-center"
        )}
      >
        <Providers>
          <header>
            <Navbar />
          </header>
          <main className="flex h-full">
            {children}
            <Toaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}
